export const medicareData = {
  data: [
    {
      voicemail_box: {
        label: 'FDL EGR CENTRAL PDP',
        value: 'FDL EGR CENTRAL PDP',
      },
      voicemail_id: 'VoiceMail10001',
      received_date: '20/04/2022',
      received_time: '08:56',
      sla_turnaround: '2022-04-21T08:56:00',
      review_status: 'Completed',
      extension_id: 'I-134435121',
      transcript:
        'I was in hospital for full hip replacement and then went to rehab. has received calls from someone that provides meals in boxes to my home, they were called GA Foods, I believe.',
      member_name: 'Manke, Paul',
      callback_no: 'I-134435121',
      call_reason: ['Benefits'],
      call_duration: '',
      audio_url: '',
      ner: {},
      reviewer: '',
      reviewer_comments: '',
      review_start_date: '20/04/2022',
      review_end_date: '20/04/2022',
    },
    {
      voicemail_box: {
        label: 'FDL EGR CENTRAL PDP',
        value: 'FDL EGR CENTRAL PDP',
      },
      voicemail_id: 'VoiceMail10002',
      received_date: '20/04/2022',
      received_time: '10:25',
      sla_turnaround: '2022-04-21T10:25:00',
      review_status: 'In Progress',
      extension_id: 'I-134811238',
      transcript:
        'My mbr # is MBL 488W00689 I injured my knee and they said I need a pre auth to get an MRI can you look up if and let them know it ok for MRI  Dr Spencer 5622399210 Ruth Dill ',
      member_name: 'Sabel, Denise',
      callback_no: '5622399210',
      call_reason: ['Authorization', 'Benefits'],
      call_duration: '',
      audio_url: '',
      ner: {},
      reviewer: '',
      reviewer_comments: '',
      review_start_date: '20/04/2022',
      review_end_time: '',
    },
    {
      voicemail_box: {
        label: 'FDL EGR CENTRAL PDP',
        value: 'FDL EGR CENTRAL PDP',
      },
      voicemail_id: 'VoiceMail10003',
      received_date: '20/04/2022',
      received_time: '11:13',
      sla_turnaround: '2022-04-21T11:13:00',
      review_status: 'In Progress',
      extension_id: 'I-134696210',
      transcript:
        'My name is Hisae Kubota MBL 023M98495 I would like to know if this card, I was told is not valid anymore, please call me 3108097438',
      member_name: 'Dykes, Andrea',
      callback_no: '3108097438',
      call_reason: ['ID Card'],
      call_duration: '',
      audio_url: '',
      ner: {},
      reviewer: '',
      reviewer_comments: '',
      review_start_date: '',
      review_end_time: '',
    },
    {
      voicemail_box: {
        label: 'FDL EGR CENTRAL PDP',
        value: 'FDL EGR CENTRAL PDP',
      },
      voicemail_id: 'VoiceMail10004',
      received_date: '20/04/2022',
      received_time: '14:20',
      sla_turnaround: '2022-04-21T14:20:00',
      review_status: 'Pending',
      extension_id: 'I-134813160',
      transcript:
        "This Annette Pratte today is 6/12/21 I'm here at the chiropractor for urgent care, I hope to be finished by 7/31 3236334835 so I understand that I have coverage thru the end of June, I already wrote to SS for reenrollment and they put me on a premium plan .I'm seeing the Dr today,  I'm hoping I have coverage for these treatments. IF not I guess I will have to pay OOP. I will call back on Monday to see if I need a medigap policy I'm not really sure what that is my mbr ID 652M98435 bye bye",
      member_name: 'Timblin, Brittany',
      callback_no: '3236334835',
      call_reason: ['Membership/Enrollment', 'Benefits'],
      call_duration: '',
      audio_url: '',
      ner: {},
      reviewer: '',
      reviewer_comments: '',
      review_start_date: '',
      review_end_time: '',
    },
    {
      voicemail_box: {
        label: 'FDL EGR CENTRAL PDP',
        value: 'FDL EGR CENTRAL PDP',
      },
      voicemail_id: 'VoiceMail10005',
      received_date: '20/04/2022',
      received_time: '15:53',
      sla_turnaround: '2022-04-21T15:53:00',
      review_status: 'Pending',
      extension_id: 'I-134808059',
      transcript:
        "My name karen G kimura MBL 930M98404 9294745174 inq about an Xray of the abdomen 2/23/21 received a bill for $36.00 mountain imaging center, when I called last month they said it was covered by my ins. I don't see that it has been. Calling to see what the delay may be. Please call me back.",
      member_name: 'Timblin, Brittany',
      callback_no: '9294745174',
      call_reason: ['Claim'],
      call_duration: '',
      audio_url: '',
      ner: {},
      reviewer: '',
      reviewer_comments: '',
      review_start_date: '',
      review_end_time: '',
    },
  ],
};
