export const Login = {
  AUTHENTICATE_USER_LOGIN: 'AUTHENTICATE_USER_LOGIN',
};

export const VoiceMailReview = {
  VOICE_MAIL_REVIEW: 'VOICE_MAIL_REVIEW',
  VOICE_MAIL_REVIEW_STAT: 'VOICE_MAIL_REVIEW_STAT',
  REASON_FOR_CALL: 'REASON_FOR_CALL',
  VOICE_MAIL_BOX: 'VOICE_MAIL_BOX',
  VOICE_MAIL_UPDATE: 'VOICE_MAIL_UPDATE',
  VOICE_MAIL_REVIEW_DOWNLOAD: 'VOICE_MAIL_REVIEW_DOWNLOAD',
};

export const CommonResponse = {
  INIT: 'INIT',
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
  PROMISEERROR: 'PROMISEERROR',
};
